theme = "modus"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
shell = ["fish", "-c"]
trim-final-newlines = true
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
rainbow-brackets = true

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace.characters]
tab = "→"

[editor.whitespace.render]
tab = "all"


[keys.normal]
"{" = "goto_next_paragraph"
"}" = "goto_prev_paragraph"
tab = "rotate_view"
"A-q" = ":wbc"
"A-tab" = "goto_next_buffer"
ret = "goto_word"

[keys.normal.space.space]
f = ":sh zellij run -n Yazi -c -f -x 5%% -y 5%% --width 90%% --height 90%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
v = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh vsplit %{buffer_name}"
d = ":yank-diagnostic"
c = ":sh chezmoi apply --force"
n = ":sh notes"

[keys.select]
"ret" = "extend_to_word"
