theme = "cat"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
shell = ["fish", "-c"]
trim-final-newlines = true
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.whitespace.characters]
tab = "→"

[editor.whitespace.render]
tab = "all"

[keys.normal]
tab = "rotate_view"
"A-q" = ":wbc"
"A-tab"="goto_next_buffer"
ret = "goto_word"


[keys.normal.C-y]
space = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
v = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh vsplit %{buffer_name}"
h = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh hsplit %{buffer_name}"


[keys.select]
"ret" = "extend_to_word"

[keys.normal.space]
space = "align_view_center"

[keys.normal.space.","]
d = ":yank-diagnostic"
c = ":sh chezmoi apply"
n = ":open ~/misc/notes/quicknotes.md"


# [keys.normal.g]
# ret = "goto_word"
# l = "goto_word"

# [keys.select.g]
# ret = "extend_to_word"
