fork = true
frame = "full"
idle = true
maximized = true
no-multigrid = false
tabs = true
theme = "auto"
neovim-bin = "/usr/bin/nvim"
title-hidden = true
vsync = false
wsl = false

[font]
normal = [
  "JetBrainsMono Nerd Font",
] # Will use the bundled Fira Code Nerd Font by default
size = 16.0
