fork = true
frame = "full"
idle = true
maximized = true
no-multigrid = false
tabs = true
theme = "auto"
neovim-bin = "/usr/bin/nvim"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["JetBrainsMono Nerd Font Mono"]
size = 16.0
