# Created by: archinstall
# Created on: 2024-03-23_00-52-52
title   Arch Linux (linux)
linux   /vmlinuz-linux-cachyos
initrd  /intel-ucode.img
initrd  /initramfs-linux-cachyos.img
options root=PARTUUID=15a8e0d0-2e24-461a-a965-c30601b8c98e zswap.enabled=0 rw rootfstype=ext4 nowatchdog mitigations=off nopti tsx=on
